nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    RATE_LIMITER_DISABLED: true

  keyvaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key-preview
          alias: app-insights-instrumentation-key
        - name: app-insights-connection-string-preview
          alias: app-insights-connection-string
        - redis-access-key
        - idam-systemupdate-username
        - idam-systemupdate-password
        - idam-ui-secret

idam-pr:
  enabled: true
  redirect_uris:
    sptribs-frontend:
      - https://${SERVICE_FQDN}/receiver
