services:
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientSecret: IDAM_SECRET
  case:
    url: CCD_URL
  payments:
    url: PAYMENTS_API_URL
  feeLookup:
    url: FEE_LOOKUP_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
  sptribs:
    url: CASE_API_URL
port: PORT
session:
  redis:
    host: REDIS_HOST
  secureCookie: SECURE_COOKIE
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
api:
  serviceAuth: RPE_API
