security:
  referrerPolicy: 'origin'
port: 3100
timeout: 30000
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  name: 'sptribs_dss_update_case_web'
  maxAge: 1260000
  PORT: 6380
  TLS: true
  CONNECTION_TIMEOUT: 15000
  COOKIE_MAX_AGE: 21
  redis:
    host:
    key:
  secureCookie: 'true'
api:
  serviceAuth: RPE_API
uploadPolicy:
  documentSize: 500
  maxNoOfFiles: 20
app:
  caseTypeOfApplication: 'RELADOP'
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
s2s:
  microservice: 'sptribs_dss_update_case_web'
documentManagement:
  uploadSizeinMB: 30
cookies:
  expiryTime: 365
  cookieName: 'sptribs-dss-update-case-web-cookie-preferences'
loggedInUsers: ['legalRep', 'police']
services:
  sptribs:
    url: 'http://sptribs-case-api-aat.service.core-compute-aat.internal'
  case:
    url: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'sptribs-dss-update-case-web'
    clientSecret: 'DUMMY_VALUE_REPLACE'
    systemUsername: 'DUMMY_VALUE_REPLACE'
    systemPassword: 'DUMMY_VALUE_REPLACE'
    caching: 'false'
dynatrace:
  dynatraceUrl: 'https://js-cdn.dynatrace.com/jstag/17177a07246/bf24054dsx/6664b4fa41dce90c_complete.js'
