security:
  referrerPolicy: 'origin'
port: 3100
timeout: 30000
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  name: 'sptribs_dss_update_case_web'
  PORT: 6380
  TLS: true
  CONNECTION_TIMEOUT: 15000
  COOKIE_MAX_AGE: 21
  redis:
    host:
    key:
  secureCookie: 'false'
api:
  serviceAuth: 'http://rpe-service-auth-provider-demo.service.core-compute-demo.internal'
uploadPolicy:
  documentSize: 20
  multimediaSize: 500
  maxNoOfFiles: 10
app:
  caseTypeOfApplication: 'RELADOP'
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
s2s:
  microservice: 'sptribs_dss_update_case_web'
documentManagement:
  uploadSizeinMB: 30
cookies:
  expiryTime: 365
  cookieName: 'sptribs-dss-update-case-web-cookie-preferences'
loggedInUsers: ['legalRep', 'police']
